# see example https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
site_name: Chao's Docs
# docs.chaodev.app
site_url: https://www.chaodev.com/

theme:
  name: material
  #   https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    primary: indigo
    accent: orange
  features:
    - instant
    - tabs
  icon:
    repo: fontawesome/brands/github
    font:
      text: Roboto
      code: Roboto Mono
# custom_dir: overrides

# extra css and js
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

# Repository
repo_name: chaochen/docs
repo_url: https://github.com/JonathanChaochen/gis-docs
# edit_uri: ""

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JonathanChaochen

# Page tree
nav:
  - Home: index.md
  - Getting started:
      - Installation: getting-started.md
      - Creating your site: creating-your-site.md
  - Environment:
      - environment.md
      - about.md

# Google Analytics
google_analytics:
  - UA-176758834-1
  - auto

# Copyright
copyright: Copyright &copy; 2020 Chao Chen
